load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "alloc",
    srcs = ["alloc.c"],
    hdrs = ["alloc.h"],
    includes = ["C:\\msys64\\mingw64\206_64-w64-mingw32\\include"],
    deps = [
        "//debug",
        "//struct:set",
    ],
)
